executable            = common/merge.sh

requirements          = (OpSysAndVer =?= "CentOS7")
on_exit_remove        = (ExitBySignal == False) && (ExitCode == 0)
max_retries           = 5
requirements = Machine =!= LastRemoteHost
+JobFlavour           = "tomorrow"
+JobBatchName         = "MERGE-$(JOBNAME)"

error                 = err/LHE/merge-$(ClusterId).$(ProcId).err

arguments             = $(FILES) $(EOSROOT) $(EOSAREA) $(PRODNAME)

queue
